#!/bin/sh
 
which golangci-lint >/dev/null 2>&1
if !([ $? -eq 0 ]); then
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
fi
 
if !(golangci-lint run --timeout=10m); then
    exit 1
fi
 
exit 0
